### ISSUE TITLE
Settings app crashes sometimes

### ISSUE THREAD

**Issue by Shetty073** [PixelExperience-Devices/device_xiaomi_ginkgo#3]
Settings app crashes sometimes while opening it and to fix it I had to do one of the following things:
* restart my device
              __or__
* clear the cache and data of the settings app
Either one will work

It is a rare scenario and I do not yet know the correct steps to replicate this issue (If it happens again I will post screenshots and steps to replicate the problem)

p.s. I don't know if this is a known problem, if yes then please ignore this issue

**Comment by Hlcpereira** [comment]
That's a known issue already, as it's ROM side, not only a device specific issue. Please notice that the device tree issues shall be used for confirmed device specific issues only. Other than what you did, you can also go for not use any different system icons to get a more definitive solution for now.

Regards.
