### ISSUE TITLE
Bluetooth and Camera not working

### ISSUE THREAD

**Issue by IlVice26** [PixelExperience-Devices/device_xiaomi_ginkgo#5]
Since the last update (2020/06/18) I found problems with the bluetooth module. When you restart the phone and turn on the bluetooth, it crashes. This doesn't allow me to have COVID-19 exposure notifications.

I also had problems with the Camera app as it doesn't save the photos in the gallery.

OT: I'm not sure if the problem is with the update, but also with Whatsapp I noticed the delay in recording voice messages. The audio is recorded after 3 seconds. I repeat, I'm not sure if it has anything to do with the system update.

**Comment by kenway27** [comment]
I have the same problem with Bluetooth

**Comment by mbeddeveloper** [comment]
Same issue

**Comment by KoteFEELS** [comment]
yes, same

**Comment by shinesun233** [comment]
Same,the Bluetooth doesn't work at all.

**Comment by shinesun233** [comment]
> Same,the Bluetooth doesn't work at all.

It happeds on both Plus and non-Plus version.

**Comment by yuluo-ding** [comment]
I have the problem too with Plus and non-Plus version.

**Comment by Call190Now** [comment]
You guys know there's a bluetooth fix in the telegram group, right?

the voice recording fix is probably related with google assistant since it's enabled by default

**Comment by yuluo-ding** [comment]
> You guys know there's a bluetooth fix in the telegram group, right?
> 
> the voice recording fix is probably related with google assistant since it's enabled by default

Sorry, I don't know this. 
Can u give me the link?
Thanks.

**Comment by Call190Now** [comment]
> > You guys know there's a bluetooth fix in the telegram group, right?
> > the voice recording fix is probably related with google assistant since it's enabled by default
> 
> Sorry, I don't know this.
> Can u give me the link?
> Thanks.

You can use [this telegram link](https://t.me/PixelExperience_GW/14384) or [this gDrive one](https://drive.google.com/file/d/14nH8lg_fQbd1_79g7KTNldrmmj7kOJwG/view) that's just a mirror I made lol
