### ISSUE TITLE
Top speaker sometimes doesnt work (Redmi Note 8)

### ISSUE THREAD

**Issue by miguela7x** [PixelExperience-Devices/device_xiaomi_ginkgo#8]
Hi, i've installed Pixel Experience on my Redmi note 8, all seems good, but when i recibe a call, i have to enable and disable the speaker because the top speaker doesnt work, i cant hear to the other person until i do this action.
Please check this issue, 
it's annoying to do this every time i recibe a call.

**Comment by miguela7x** [comment]
o forgot to mention this,
i installed this rom:

 PixelExperience_Plus_ginkgo-10.0-20201014-0012-OFFICIAL.zip

**Comment by Lexan92** [comment]
> Hi, i've installed Pixel Experience on my Redmi note 8, all seems good, but when i recibe a call, i have to enable and disable the speaker because the top speaker doesnt work, i cant hear to the other person until i do this action.
> Please check this issue, 
> it's annoying to do this every time i recibe a call.

I have the same issue
